# Generated by Django 5.0.7 on 2024-08-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default="Hey, there I'm using PhysiXplorer!", null=True),
        ),
    ]
