# Generated by Django 5.0.7 on 2024-08-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default="Hey, there I'm using PhysiXplorer!", null=True),
        ),
    ]
